name       : soci
version    : 4.0.1
release    : 4
source     :
    - https://github.com/SOCI/soci/archive/4.0.1.tar.gz : fa69347b1a1ef74450c0382b665a67bd6777cc7005bbe09726479625bcf1e29c
homepage   : http://soci.sourceforge.net/
license    : BSL-1.0
component  : database
summary    : Official repository of the SOCI - The C++ Database Access Library
description: |
    SOCI is a database access library for C++ that makes the illusion of embedding SQL queries in the regular C++ code, staying entirely within the Standard C++.
builddeps  :
    - pkgconfig(libpq)
    - pkgconfig(sqlite3)
    - libboost-devel
setup      : |
    %cmake_ninja \
        -DCMAKE_CXX_STANDARD=11 \
        -DSOCI_TESTS=OFF \
        -DSOCI_EMPTY=OFF \
        -DSOCI_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
